apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.mongodb.persistentVolume.name }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: {{ .Values.mongodb.persistentVolume.storage }}
  hostPath:
    path: {{ .Values.mongodb.persistentVolume.path }}
