apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.policyAgent.configMap.name }}
data:
  {{- range $k,$v := .Values.policyAgent.configMap.data }}
  {{ $k }}: |
{{ $.Files.Get $v | indent 4 }}
  {{- end }}
